version: "3"

services:
  atmoz-sftp:
    container_name: atmoz-sftp
    hostname: atmoz-sftp
    image: atmoz/sftp
    volumes:
      - ./upload:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001