version: "3"

services:
  atmoz-sftp:
    image: atmoz/sftp
    container_name: atmoz-sftp
    hostname: atmoz-sftp
    volumes:
      - ./upload:/home/foo/upload
      - ./keys/client/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
      - ./keys/host/host_id_rsa.pub:/etc/ssh/ssh_host_rsa.pub
      - ./keys/host/host_id_rsa:/etc/ssh/ssh_host_rsa_key
    ports:
      - "2222:22"
    command: foo:1001