micronaut:
  application:
    name: jsch-atmoz-sftp-poc

sftp:
  upload-folder: upload
  client:
    user: foo
    public-key: AAAAB3NzaC1yc2EAAAADAQABAAABgQCtdSAyAqdUu9WvJE+GeiNVaBAIPX5fLmaL5kHRTWeioQMovW27N4jMuz9xoGj6vxMyw5XUAeRgQwHRnyjVjXkT3Fjq4zfRzwLXBfD10mQUPijf3APQwVvkndqLwuKSYM0BUv7tdOSOGBHXmIr6LYzQ93hS2uctzYhvt8GZSvxa0CeY9FHTVyrcbrHLfJQnAXL3UeOYFQ+wL2nwrAVinkXrfWBGtsKbSYSiND7PGljw/ZPh8o1SMEEy8kbIY88VeTIvQajF8LaGoYLRGxpCqDUv4BGK8ofXzvGgt+6FnH6m2cRFuQzwqHocstEZo1badf9QWw/UU71SC6xsUxAdnrQcPsIyetvKkWXqy+eEl0NBgYzozZS5F4QcY6e6zfNrl58mYDMnm0YmMcr62QFx3di3RAjlw9pSAVo2IhBs5RpRQTya6xPdjYntL2Zpm2JqRTFlGswvoEmBqo7nCN1P9aIDp0uXRTOfeb3v6au+ip8gG3LDDyVC3AQ2hTG7IhhcIqs=
    private-key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIG4wIBAAKCAYEArXUgMgKnVLvVryRPhnojVWgQCD1+Xy5mi+ZB0U1noqEDKL1t
      uzeIzLs/caBo+r8TMsOV1AHkYEMB0Z8o1Y15E9xY6uM30c8C1wXw9dJkFD4o39wD
      0MFb5J3ai8LikmDNAVL+7XTkjhgR15iK+i2M0Pd4UtrnLc2Ib7fBmUr8WtAnmPRR
      01cq3G6xy3yUJwFy91HjmBUPsC9p8KwFYp5F631gRrbCm0mEojQ+zxpY8P2T4fKN
      UjBBMvJGyGPPFXkyL0GoxfC2hqGC0RsaQqg1L+ARivKH187xoLfuhZx+ptnERbkM
      8Kh6HLLRGaNW2nX/UFsP1FO9UgusbFMQHZ60HD7CMnrbypFl6svnhJdDQYGM6M2U
      uReEHGOnus3za5efJmAzJ5tGJjHK+tkBcd3Yt0QI5cPaUgFaNiIQbOUaUUE8musT
      3Y2J7S9maZtiakUxZRrML6BJgaqO5wjdT/WiA6dLl0Uzn3m97+mrvoqfIBtyww8l
      QtwENoUxuyIYXCKrAgMBAAECggGAY0nqNfZC5kPm2yxDwUxksVyx4KWiksUyud4B
      ytct/W+BKW7VQxdU3SxJ8rbJoM6DJMnEF+lFWrzAa8dZTnR+3BmDZGDP8O84RvEF
      rxDRbKzwJMQCAxrLiR+6m8nge72hW6KwfigtNBEfFXQiCXbNZkhhvbvEHPnLoXdk
      AGVl8m24XNttgzYgOLG8YChdfb5cmqlrSAC2TDm3wKYXJw5GI7hOxeuTleQNYfPa
      CB6izr+4SNvYfTVV/N2mGsrXHQmT+QcmFFDP/VGbwatAlubBjjAWNFxkpnmFi35n
      DvN+hHmjpNc2tz/Uyoabz1WDKfU8mEehLpBi0EoHqwFT+fgvFSf6eW13i6x6L/8v
      QNYsYeCZduwEPR3hu+n8LVy0IkV1btZkuvQ7LEX8BrfonamIXk7E6yuEuu0dAOZA
      LFi8sQ0y3qXiW6eSb1CB38/rPBXBp46PzhMlZV3MDWjhk7QLIoqfCBM/QJkIeCBS
      ldQSsYTB50l8jX4Mmcic1uxAoYyBAoHBANpVIOYUERWhkdyzt5uYGxlTpMDWxFCZ
      BTDru5qT+fHZ71hd6y9vn71gUiQ2YW2S5gmMM6jX1/KWOSM695ObPjGIowXn0a/6
      Vdjd+UWiry/FkYpiKbH/nX6AZs1ZsHJmQjcE+iUF8bYfgjo0eXYcbV01q1i3hzF4
      Ar5R1S2RTDWmYS+va43JIevv6LRPNJjSsAxGuh4bWLvLHetZn+pdiU8gfFRWpi0q
      K3hff6GhK4peiRnGojSlCaKEZhaCTKFUIQKBwQDLYgxVkmXTeXwvcHIu6ITWkWrj
      quLN01CfGlFRL8K9DPzizM+hUonp3p6+7s38TNBwcoGO0Zx1mqfdeJGMl4lst6An
      bexbSFc3DpGWf8S5ktnBqNPFK+rA6TefuK8FFU3kgdYljqQuVWd4Szi+o0Gr0KBH
      EhW/eKZ9wWbx6IlZdaAQUSWGD3US5wPaw24dbxTSJWef+R4w1u3GPsyFnZBQeRiW
      s+yd40Cfy/A1tM6DI56i9+EV0A6L8T7yUPB43UsCgcA43vnN1KZKmyZydcG63tkY
      NMhyjr7eO621e4IHlsoBbIJC41vypEHYw3FCC4Q/VYdkL0f5kBepEeZaPe7lXQfL
      QUstq5/cFfosnk1jDShS6kSp5j30JqAwpmOg0975PZe72ykJYc3/YZ+7Z5XH5Um7
      gNJcLpohkaAtUQWVdAaE5wzjre73JNAYNArKhOMvd5nx6K5sTzVC3XqypkrYcnrk
      yJJ6KYPpudVO6plFUcUUquFNfIcd7WtgENrCvDgXweECgcEAgYuib58gXOM0xsLI
      +DgC5OkbPIjMjm3bHHyW7y+Myv5K1eu/FPKOBflXBCb37Yy/99/3xhCdqAsqgVca
      3oJndmhACt1pf3tEkj0lXsdjdxCiw0fWG/EtRlNGquXoFUTMqJBK5wFEcn7TuTuw
      mT1DxzzL2nkagStIYTGfcNa9Jc5Wdg456HpQCAo92kpBCV6H1JMevjbflBxSt8Oo
      YjNKiPeZQeS5ApiNwTsVdiAEqmM12HgrVsl/eoPfpFkJ0vKhAoHAW5bGHnv+xXbH
      JXueir6oZ6ACCGsVllCVMciRWvr417yFzvJUbChCoiCcrwgKxYvqPQpA7VC330DM
      qqiwbk6SmX6Z1NQ8zQuJvccnb0kDykzvfEkXJ6wPDbX7QwbXdDVpUlQ5456iImRm
      jSOZw4KMejbTTHy0p58i9wOEtmaOdWBs9hQgaOc6+TEqNdR968Gl/O4NuU5UPBp1
      DnSpB+ZC70SQRp6Xxpe/w6Y72OKvxp1AlcOEuJJ1p3HwVJXLMFgQ
      -----END RSA PRIVATE KEY-----
  server:
    host: localhost
    port: 2222
    public-key: AAAAB3NzaC1yc2EAAAADAQABAAABgQC5pygNTxmJ6WtA0Xbw/PBJ6nYteD2BLzwQZIXD11KkBzjIrFj4DIVgGM5EhnSKsVMhrXrx9vL8iHBP20+EE/TLx7NeBJRh3mIUoABx9mzqkwleB2nReji7vDCGqUvmkM+evqCqktCpXuchztNkl0Sb/33RdhMezUwgcNBVUAnlMDurAJC/xUdhECY5nmhQTnzqbaDSr0Sr14aLW+jFxRi6vD45Mkxo044FKflAyoiMJv6fi3U8FDhZJl3OQsA8kf+pFDEMrmFW9+uOxvqh1FlQr2J0ObYIF9mFkfeMrw/8Ht6OpClSifmKdla4gYzwOLmPoDU7UfRS17MtQJ60Fk6kOYWFTe+F5rARc9HOTATDXpUC965wcuYZkptrLMuoSvIvsSSb6ZK7qJNr0+feaJna6VbacZZiO468GFT/Wy0qN7cbHH2uXr4djfh5mvu9n0fjQu829FvFovk7kTM9v5w1QQLEue7QGgJl7USl+bJ4Nlh3y+dQLsW+zSfOcx1xRsc=